apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: outer-loop
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: outer-loop
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/outer-loop
      ref:
        branch: main